version: '2'
services:
  scrapyd:
    image: registry.cn-shenzhen.aliyuncs.com/jiayi/scrapyd:1.0.0
    ports:
      - "6800:6800"
    volumes:
      - /var/run/scrapyd:/var/lib/scrapyd
  scrapydweb:
    image:  registry.cn-shenzhen.aliyuncs.com/jiayi/scrapydweb:latest
    depends_on:
      - scrapyd
    ports:
      - "5000:5000"
    volumes:
      - /var/run/scrapyd:/var/lib/scrapyd
      - ./scrapydweb_settings_v8.py:/opt/scrapydweb_settings_v8.py
    environment:
      TZ: Asia/Shanghai

  
