version: '2'
services:
  scrapyd:
    image: registry.cn-shenzhen.aliyuncs.com/jiayi/scrapyd:latest
    hostname: default_scrapyd
    ports:
      - "6800:6800"
    volumes:
      - /var/run/scrapyd:/var/lib/scrapyd
  scrapydweb:
    image:  registry.cn-shenzhen.aliyuncs.com/jiayi/scrapydweb:latest
    depends_on:
      - scrapyd
    ports:
      - "5000:5000"

    volumes:
      #- /var/run/scrapyd:/var/lib/scrapyd
      - ./scrapydweb_settings_v10.py:/opt/scrapydweb_settings_v10.py
    environment:
      TZ: Asia/Shanghai
      DEBUG: 1

  
